# /// script
# requires-python = ">=3.11"
# ///
"""
install.py — Symlink agent configs to the right locations for each tool.

Usage:
    python install.py [--dry-run] [--force]

Reads install.toml (copy from install.toml.example and edit). For each enabled tool:
  - Symlinks shared/SYSTEM-INSTRUCTIONS.md to the tool's user instruction file path
  - Symlinks skills/general/* to ~/.agents/skills (cross-tool standard) and to ~/.claude/skills (Claude only)
  - For Claude (detected by presence of 'agents' key): also links skills/claude/* and agents/*.md
  - Regenerates skills/INDEX.md from SKILL.md frontmatter (human reference only; agents discover via SKILL.md)

Safety:
  - Idempotent: re-running is always safe
  - Existing regular files are backed up before replacement
  - Foreign symlinks (pointing elsewhere) are skipped unless --force
"""

import argparse
import tomllib
from datetime import datetime
from pathlib import Path


def parse_frontmatter(skill_path: Path) -> dict:
    text = skill_path.read_text()
    if not text.startswith("---"):
        return {}
    try:
        end = text.index("---", 3)
    except ValueError:
        return {}
    result = {}
    for line in text[3:end].splitlines():
        if ":" in line:
            k, _, v = line.partition(":")
            result[k.strip()] = v.strip()
    return result


def link(src: Path, dst: Path, dry_run: bool, force: bool) -> str:
    if dst.is_symlink():
        if dst.resolve() == src.resolve():
            return "already linked"
        if not force:
            return f"SKIPPED (points to {dst.resolve()}; use --force)"
        if dry_run:
            return f"would replace foreign symlink → {dst}"
        dst.unlink()
    elif dst.exists():
        if dry_run:
            return f"would backup and replace → {dst}"
        timestamp = datetime.now().strftime("%Y%m%dT%H%M%S")
        backup = dst.parent / (dst.name + f".bak.{timestamp}")
        dst.rename(backup)
        print(f"    backed up → {backup.name}")

    if dry_run:
        return f"would link → {dst}"

    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.symlink_to(src)
    return "created"


def generate_index(repo_root: Path) -> str:
    general_skills: list[tuple[str, str]] = []
    claude_skills: list[tuple[str, str]] = []

    general_dir = repo_root / "skills" / "general"
    claude_dir = repo_root / "skills" / "claude"

    if general_dir.exists():
        for skill_md in sorted(general_dir.rglob("SKILL.md")):
            fm = parse_frontmatter(skill_md)
            if fm.get("name") and fm.get("description"):
                general_skills.append((fm["name"], fm["description"]))

    if claude_dir.exists():
        for skill_md in sorted(claude_dir.rglob("SKILL.md")):
            fm = parse_frontmatter(skill_md)
            if fm.get("name") and fm.get("description"):
                claude_skills.append((fm["name"], fm["description"]))

    lines = [
        "<!-- AUTO-GENERATED by install.py — DO NOT EDIT. Human reference only; agents discover skills via SKILL.md frontmatter, not this file. -->",
        "# Skills Index",
        "",
        "## General Skills (all tools)",
        "",
    ]
    for name, desc in general_skills:
        lines.append(f"- **{name}**: {desc}")
    if not general_skills:
        lines.append("_(none yet)_")
    lines += ["", "## Claude Code Skills", ""]
    for name, desc in claude_skills:
        lines.append(f"- **{name}**: {desc}")
    if not claude_skills:
        lines.append("_(none yet)_")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Install agent config symlinks")
    parser.add_argument("--dry-run", action="store_true", help="Preview without making changes")
    parser.add_argument("--force", action="store_true", help="Replace foreign symlinks")
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parent
    toml_path = repo_root / "install.toml"

    if not toml_path.exists():
        print("Error: install.toml not found.")
        print("Run: cp install.toml.example install.toml  then edit it.")
        raise SystemExit(1)

    with open(toml_path, "rb") as f:
        config = tomllib.load(f)

    tools = config.get("tools", {})
    results: list[tuple[str, str, str, str]] = []

    for tool_name, tool_config in tools.items():
        if not tool_config.get("enabled", False):
            continue

        is_claude = "agents" in tool_config

        # User-level instruction file
        if "instructions" in tool_config:
            src = repo_root / "shared" / "SYSTEM-INSTRUCTIONS.md"
            dst = Path(tool_config["instructions"]).expanduser()
            status = link(src, dst, args.dry_run, args.force)
            results.append((tool_name, "shared/SYSTEM-INSTRUCTIONS.md", str(dst), status))

        # Skills directories
        skills_dst_raw = tool_config.get("skills")
        if skills_dst_raw:
            skills_dst = Path(skills_dst_raw).expanduser()

            general_dir = repo_root / "skills" / "general"
            if general_dir.exists():
                for skill_dir in sorted(general_dir.iterdir()):
                    if skill_dir.is_dir() and not skill_dir.name.startswith("."):
                        dst = skills_dst / skill_dir.name
                        status = link(skill_dir, dst, args.dry_run, args.force)
                        results.append((tool_name, f"skills/general/{skill_dir.name}", str(dst), status))

            if is_claude:
                claude_dir = repo_root / "skills" / "claude"
                if claude_dir.exists():
                    for skill_dir in sorted(claude_dir.iterdir()):
                        if skill_dir.is_dir() and not skill_dir.name.startswith("."):
                            dst = skills_dst / skill_dir.name
                            status = link(skill_dir, dst, args.dry_run, args.force)
                            results.append((tool_name, f"skills/claude/{skill_dir.name}", str(dst), status))

        # Agent files (Claude only)
        if is_claude:
            agents_dst = Path(tool_config["agents"]).expanduser()
            agents_src_dir = repo_root / "agents"
            if agents_src_dir.exists():
                for agent_file in sorted(agents_src_dir.glob("*.md")):
                    dst = agents_dst / agent_file.name
                    status = link(agent_file, dst, args.dry_run, args.force)
                    results.append((tool_name, f"agents/{agent_file.name}", str(dst), status))

    # Regenerate INDEX.md
    index_path = repo_root / "skills" / "INDEX.md"
    index_content = generate_index(repo_root)
    if not args.dry_run:
        index_path.write_text(index_content)
        results.append(("—", "skills/INDEX.md", str(index_path), "generated"))
    else:
        results.append(("—", "skills/INDEX.md", str(index_path), "would generate"))

    # Summary
    print()
    if args.dry_run:
        print("DRY RUN — no changes made\n")
    col_w = 14
    src_w = 38
    print(f"{'Tool':<{col_w}} {'Source':<{src_w}} Status")
    print("-" * (col_w + src_w + 30))
    for tool, src, dst, status in results:
        print(f"{tool:<{col_w}} {src:<{src_w}} {status}")
    print()


if __name__ == "__main__":
    main()
